module

public import Isaacs.CoprimeQuotients

/-!
# The commutator of a coprime action

Isaacs, *Finite Group Theory*, Lemmas 4.28 and 4.29:

* `CoprimeAction.fixedPoints_sup_commutatorAction_eq_top` (4.28): if `(|G|,|A|) = 1` and one of
  `A`, `G` is solvable, then `G = C_G(A)⁅G, A⁆`;
* `CoprimeAction.commutatorAction₂_eq` (4.29): if `(|G|,|A|) = 1` then `⁅G, A, A⁆ = ⁅G, A⁆`, with
  no solvability hypothesis.

`⁅H, A⁆` is `CoprimeAction.commutatorSubgroup`, the subgroup generated by the elements
`h⁻¹ * (a • h)`; the naming and the convention agree with the Qiuzhen CFSG development's
`commutatorSubgroup` / `commutatorAction` / `commutatorAction₂`, whose
`FeitThompson/GroupAction/CoprimeHall.lean` proves both statements under the stronger hypothesis
that `G` is solvable.  `mathlib` has no commutator for an action at all.

4.28 is 3.28 applied to `N = ⁅G, A⁆`, on whose quotient `A` acts trivially by construction.  4.29
follows for solvable `A` from 4.28, and in general by applying that case to the cyclic — hence
solvable — subgroup `⟨a⟩` of `A`, which is Isaacs' argument.
-/

@[expose] public section

namespace CoprimeAction

open scoped Pointwise

universe u

variable {G A : Type u} [Group G] [Group A] [MulDistribMulAction A G]

/-!
## The commutator subgroup of an action
-/

/-- The commutator `⁅H, A⁆` of a subgroup `H ≤ G` with the action of `A`: the subgroup generated
by the elements `h⁻¹ * (a • h)` for `h ∈ H` and `a ∈ A`. -/
def commutatorSubgroup (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G]
    (H : Subgroup G := ⊤) : Subgroup G :=
  Subgroup.closure {x : G | ∃ a : A, ∃ h : G, h ∈ H ∧ x = h⁻¹ * (a • h)}

/-- The commutator `⁅G, A⁆` of the whole group with the action. -/
abbrev commutatorAction (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G] :
    Subgroup G := commutatorSubgroup A G ⊤

/-- The iterated commutator `⁅G, A, A⁆`. -/
abbrev commutatorAction₂ (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G] :
    Subgroup G := commutatorSubgroup A G (commutatorAction A G)

theorem mem_commutatorSubgroup_gen {H : Subgroup G} (a : A) {h : G} (hh : h ∈ H) :
    h⁻¹ * (a • h) ∈ commutatorSubgroup A G H :=
  Subgroup.subset_closure ⟨a, h, hh, rfl⟩

theorem commutatorSubgroup_le {H K : Subgroup G}
    (hgen : ∀ (a : A), ∀ h ∈ H, h⁻¹ * (a • h) ∈ K) : commutatorSubgroup A G H ≤ K := by
  refine Subgroup.closure_le _ |>.mpr ?_
  rintro x ⟨a, h, hh, rfl⟩
  exact hgen a h hh

/-- `⁅G, A⁆` is `A`-invariant: `b • ⁅g, a⁆ = ⁅b • g, bab⁻¹⁆`. -/
theorem smul_mem_commutatorAction (b : A) {n : G} (hn : n ∈ commutatorAction A G) :
    b • n ∈ commutatorAction A G := by
  induction hn using Subgroup.closure_induction with
  | mem y hy =>
    obtain ⟨a, h, -, rfl⟩ := hy
    have key : b • (h⁻¹ * (a • h)) = (b • h)⁻¹ * ((b * a * b⁻¹) • (b • h)) := by
      rw [smul_mul', smul_inv', ← mul_smul, ← mul_smul]
      congr 2
      group
    rw [key]
    exact mem_commutatorSubgroup_gen _ (Subgroup.mem_top _)
  | one => simp
  | mul y z _ _ hy hz =>
    rw [smul_mul']
    exact mul_mem hy hz
  | inv y _ hy =>
    rw [smul_inv']
    exact inv_mem hy

/-- `⁅G, A⁆` is normal in `G`: `⁅gx, a⁆ = ⁅g, a⁆ˣ ⁅x, a⁆`. -/
instance commutatorAction_normal : (commutatorAction A G).Normal := by
  constructor
  intro n hn x
  induction hn using Subgroup.closure_induction with
  | mem y hy =>
    obtain ⟨a, h, -, rfl⟩ := hy
    have hexp : a • (h * x⁻¹) = (a • h) * (a • x⁻¹) := smul_mul' a h x⁻¹
    have key : x * (h⁻¹ * (a • h)) * x⁻¹
        = ((h * x⁻¹)⁻¹ * (a • (h * x⁻¹))) * ((x⁻¹)⁻¹ * (a • x⁻¹))⁻¹ := by
      rw [hexp]
      group
    rw [key]
    exact mul_mem (mem_commutatorSubgroup_gen a (Subgroup.mem_top _))
      (inv_mem (mem_commutatorSubgroup_gen a (Subgroup.mem_top _)))
  | one => simp
  | mul y z _ _ hy hz =>
    have hrw : x * (y * z) * x⁻¹ = (x * y * x⁻¹) * (x * z * x⁻¹) := by group
    rw [hrw]
    exact mul_mem hy hz
  | inv y _ hy =>
    have hrw : x * y⁻¹ * x⁻¹ = (x * y * x⁻¹)⁻¹ := by group
    rw [hrw]
    exact inv_mem hy

theorem smul_mem_commutatorAction' : ∀ (a : A), ∀ n ∈ commutatorAction A G,
    a • n ∈ commutatorAction A G := fun a _ hn ↦ smul_mem_commutatorAction a hn

/-- By construction, `A` acts trivially on `G ⧸ ⁅G, A⁆`. -/
theorem smul_mk_commutatorAction (a : A) (x : G ⧸ commutatorAction A G) :
    letI := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
    a • x = x := by
  let := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
  induction x using QuotientGroup.induction_on with
  | _ y =>
    rw [quotientAction_mk]
    refine QuotientGroup.eq.mpr ?_
    have hmem : y⁻¹ * (a • y) ∈ commutatorAction A G :=
      mem_commutatorSubgroup_gen a (Subgroup.mem_top _)
    simpa using inv_mem hmem

/-- `⁅G, A, A⁆ ≤ ⁅G, A⁆`, since `⁅G, A⁆` is `A`-invariant. -/
theorem commutatorAction₂_le : commutatorAction₂ A G ≤ commutatorAction A G :=
  commutatorSubgroup_le fun a _ hh ↦ mul_mem (inv_mem hh) (smul_mem_commutatorAction a hh)

variable [Finite G] [Finite A]

/-!
## Isaacs 4.28
-/

/-- **Isaacs, Lemma 4.28.**  For a coprime action with `A` or `G` solvable, `G = C_G(A)⁅G, A⁆`. -/
theorem fixedPoints_sup_commutatorAction_eq_top (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G))
    (hsolv : Group.IsSolvable A ∨ Group.IsSolvable G) :
    FixedPoints.subgroup A G ⊔ commutatorAction A G = ⊤ := by
  let := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
  have hcop' : Nat.Coprime (Nat.card A) (Nat.card (commutatorAction A G)) :=
    Nat.Coprime.coprime_dvd_right (Subgroup.card_subgroup_dvd_card _) hcop
  have hsolv' : Group.IsSolvable A ∨ Group.IsSolvable (commutatorAction A G) :=
    hsolv.imp id fun hG ↦ by have := hG; exact inferInstance
  exact fixedPoints_sup_eq_top hSZ (smul_mem_commutatorAction' (A := A) (G := G)) hcop' hsolv'
    (quotientAction_mk _) smul_mk_commutatorAction

/-!
## Isaacs 4.29
-/

/-- Isaacs 4.29 when the operator group is solvable: if `g = cx` with `c` fixed and `x ∈ ⁅G, A⁆`
then `⁅g, a⁆ = ⁅x, a⁆`. -/
theorem commutatorAction₂_eq_of_isSolvable (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G)) (hsolvA : Group.IsSolvable A) :
    commutatorAction₂ A G = commutatorAction A G := by
  refine le_antisymm commutatorAction₂_le (commutatorSubgroup_le fun a g _ ↦ ?_)
  have hg : g ∈ (FixedPoints.subgroup A G : Set G) * (commutatorAction A G : Set G) := by
    rw [← Subgroup.mul_normal]
    rw [fixedPoints_sup_commutatorAction_eq_top hSZ hcop (Or.inl hsolvA)]
    trivial
  obtain ⟨c, hc, x, hx, rfl⟩ := hg
  have hca : a • c = c := hc a
  have key : (c * x)⁻¹ * (a • (c * x)) = x⁻¹ * (a • x) := by
    rw [smul_mul', hca]
    group
  rw [key]
  exact mem_commutatorSubgroup_gen a hx

/-- **Isaacs, Lemma 4.29.**  For any coprime action, `⁅G, A, A⁆ = ⁅G, A⁆`; no solvability is
needed, because it suffices to treat one automorphism at a time and `⟨a⟩` is cyclic. -/
theorem commutatorAction₂_eq (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G)) :
    commutatorAction₂ A G = commutatorAction A G := by
  refine le_antisymm commutatorAction₂_le (commutatorSubgroup_le fun a g _ ↦ ?_)
  -- restrict the action to the cyclic subgroup generated by `a`
  let : MulDistribMulAction (Subgroup.zpowers a) G :=
    MulDistribMulAction.compHom G (Subgroup.zpowers a).subtype
  have hcopK : Nat.Coprime (Nat.card (Subgroup.zpowers a)) (Nat.card G) :=
    Nat.Coprime.coprime_dvd_left (Subgroup.card_subgroup_dvd_card _) hcop
  have hK := commutatorAction₂_eq_of_isSolvable (A := Subgroup.zpowers a) (G := G) hSZ hcopK
    (Group.isSolvable_of_comm fun x y ↦ mul_comm' x y)
  -- the commutators for `⟨a⟩` are commutators for `A`
  have htrans : ∀ H H' : Subgroup G, H ≤ H' →
      commutatorSubgroup (Subgroup.zpowers a) G H ≤ commutatorSubgroup A G H' := by
    intro H H' hHH'
    exact commutatorSubgroup_le fun b h hh ↦ mem_commutatorSubgroup_gen (b : A) (hHH' hh)
  have h1 : g⁻¹ * (a • g) ∈ commutatorAction (Subgroup.zpowers a) G :=
    mem_commutatorSubgroup_gen (⟨a, Subgroup.mem_zpowers a⟩ : Subgroup.zpowers a)
      (Subgroup.mem_top _)
  rw [← hK] at h1
  exact htrans _ _ (htrans _ _ le_rfl) h1

/-!
## Isaacs 4.34(a): on an abelian group the fixed points meet the commutator trivially

For a coprime action on an abelian group the *norm* `g ↦ ∏ a : A, a • g` is a homomorphism.
Translating the index by `b ∈ A` does not change the product, so the norm kills every generator
`g⁻¹ * (a • g)` of `⁅G, A⁆`; on `C_G(A)` it is the `|A|`-th power map, which is injective because
`|A|` and `|G|` are coprime.  Hence `C_G(A) ⊓ ⁅G, A⁆ = 1`, which together with
`CoprimeAction.fixedPoints_sup_commutatorAction_eq_top` is Isaacs' decomposition
`G = C_G(A) × ⁅G, A⁆`.
-/

section Abelian

variable {V : Type u} [CommGroup V] [MulDistribMulAction A V]

variable (A V) in
/-- The norm map `g ↦ ∏_{a ∈ A} a • g` of an action on an abelian group. -/
def normMap [Fintype A] : V →* V where
  toFun g := ∏ a : A, a • g
  map_one' := by simp
  map_mul' g h := by
    simp only [smul_mul']
    rw [Finset.prod_mul_distrib]

omit [Finite G] [Finite A] in
theorem normMap_apply [Fintype A] (g : V) : normMap A V g = ∏ a : A, a • g := rfl

omit [Finite A] in
/-- The norm is unchanged by the action: translating the index leaves the product alone. -/
theorem normMap_smul [Fintype A] (b : A) (g : V) : normMap A V (b • g) = normMap A V g := by
  rw [normMap_apply, normMap_apply]
  calc ∏ a : A, a • (b • g) = ∏ a : A, (a * b) • g :=
        Finset.prod_congr rfl fun a _ => (mul_smul a b g).symm
    _ = ∏ a : A, a • g := Equiv.prod_comp (Equiv.mulRight b) fun a => a • g

omit [Finite A] in
/-- The norm kills `⁅G, A⁆`. -/
theorem commutatorAction_le_ker_normMap [Fintype A] :
    commutatorAction A V ≤ (normMap A V).ker := by
  refine commutatorSubgroup_le fun a g _ => ?_
  rw [MonoidHom.mem_ker, map_mul, map_inv, normMap_smul, inv_mul_cancel]

omit [Finite A] in
/-- On the fixed points the norm is the `|A|`-th power map. -/
theorem normMap_eq_pow_of_mem_fixedPoints [Fintype A] {g : V}
    (hg : g ∈ FixedPoints.subgroup A V) : normMap A V g = g ^ Nat.card A := by
  rw [normMap_apply, Finset.prod_congr rfl fun a _ => hg a, Finset.prod_const, Finset.card_univ,
    Nat.card_eq_fintype_card]

/-- **Isaacs, Lemma 4.34(a).**  For a coprime action on an abelian group, the fixed points meet
the commutator trivially. -/
theorem fixedPoints_inf_commutatorAction_eq_bot [Finite V]
    (hcop : Nat.Coprime (Nat.card A) (Nat.card V)) :
    FixedPoints.subgroup A V ⊓ commutatorAction A V = ⊥ := by
  have : Fintype A := Fintype.ofFinite A
  rw [eq_bot_iff]
  rintro x ⟨hxC, hxK⟩
  have h1 : x ^ Nat.card A = 1 := by
    rw [← normMap_eq_pow_of_mem_fixedPoints hxC]
    exact MonoidHom.mem_ker.mp (commutatorAction_le_ker_normMap hxK)
  have h2 : orderOf x ∣ Nat.card A := orderOf_dvd_of_pow_eq_one h1
  have h3 : orderOf x ∣ Nat.card V := orderOf_dvd_natCard x
  have h4 : orderOf x = 1 := Nat.dvd_one.mp (hcop ▸ Nat.dvd_gcd h2 h3)
  exact Subgroup.mem_bot.mpr (orderOf_eq_one_iff.mp h4)

/-- **Isaacs, Corollary 4.35.**  A coprime operator group on an abelian `p`-group that fixes every
element of order `p` acts trivially.

By 4.34(a) the fixed points meet `⁅V, A⁆` trivially.  If `⁅V, A⁆` were nontrivial it would be a
nontrivial `p`-group, so Cauchy would give it an element of order `p`; that element is fixed by
hypothesis, so it lies in the trivial intersection. -/
theorem commutatorAction_eq_bot_of_forall_orderOf_eq_prime [Finite V] {p : ℕ} [Fact p.Prime]
    (hV : IsPGroup p V) (hcop : Nat.Coprime (Nat.card A) (Nat.card V))
    (hfix : ∀ x : V, orderOf x = p → ∀ a : A, a • x = x) :
    commutatorAction A V = ⊥ := by
  by_contra hne
  -- a nontrivial `p`-subgroup has an element of order `p`
  have hnt : Nontrivial ↑(commutatorAction A V) :=
    (Subgroup.nontrivial_iff_ne_bot _).mpr hne
  have hp : IsPGroup p ↑(commutatorAction A V) := hV.to_subgroup _
  obtain ⟨n, hn⟩ := hp.exists_card_eq
  have hdvd : p ∣ Nat.card ↑(commutatorAction A V) := by
    rw [hn]
    refine dvd_pow_self p fun hn0 => ?_
    rw [hn0, pow_zero] at hn
    exact (Finite.one_lt_card (α := ↑(commutatorAction A V))).ne' hn
  obtain ⟨y, hy⟩ := exists_prime_orderOf_dvd_card' (G := ↑(commutatorAction A V)) p hdvd
  have hyV : orderOf (y : V) = p := by rwa [Subgroup.orderOf_coe]
  have hmem : (y : V) ∈ FixedPoints.subgroup A V ⊓ commutatorAction A V :=
    ⟨hfix (y : V) hyV, y.2⟩
  rw [fixedPoints_inf_commutatorAction_eq_bot hcop, Subgroup.mem_bot] at hmem
  rw [hmem, orderOf_one] at hyV
  exact (Fact.out : p.Prime).one_lt.ne hyV

/-- The trivial-action form of Corollary 4.35. -/
theorem smul_eq_self_of_forall_orderOf_eq_prime [Finite V] {p : ℕ} [Fact p.Prime]
    (hV : IsPGroup p V) (hcop : Nat.Coprime (Nat.card A) (Nat.card V))
    (hfix : ∀ x : V, orderOf x = p → ∀ a : A, a • x = x) (a : A) (x : V) : a • x = x := by
  have h1 : x⁻¹ * (a • x) ∈ commutatorAction A V :=
    mem_commutatorSubgroup_gen a (Subgroup.mem_top x)
  rw [commutatorAction_eq_bot_of_forall_orderOf_eq_prime hV hcop hfix, Subgroup.mem_bot,
    inv_mul_eq_one] at h1
  exact h1.symm

end Abelian

/-!
## Conjugation as an action

A subgroup normalized by `A` is an `A`-group under conjugation.  This is how the results above
get applied to a pair of subgroups of a common group.
-/

/-- Conjugation makes a subgroup normalized by `A` into an `A`-group.  (CFSG's
`Subgroup.conjMulDistribMulActionOfLeNormalizer`.) -/
@[reducible]
def conjActionOfLeNormalizer {X : Type*} [Group X] (A N : Subgroup X)
    (hAN : A ≤ Subgroup.normalizer (N : Set X)) : MulDistribMulAction A N :=
  let smulFun : A → N → N := fun a n =>
    ⟨(a : X) * (n : X) * (a : X)⁻¹, (Subgroup.mem_normalizer_iff.mp (hAN a.2) (n : X)).mp n.2⟩
  { smul := smulFun
    one_smul := by
      intro n
      change smulFun 1 n = n
      apply Subtype.ext
      simp [smulFun]
    mul_smul := by
      intro a b n
      change smulFun (a * b) n = smulFun a (smulFun b n)
      apply Subtype.ext
      simp [smulFun, mul_assoc]
    smul_mul := by
      intro a x y
      change smulFun a (x * y) = smulFun a x * smulFun a y
      apply Subtype.ext
      simp [smulFun, mul_assoc]
    smul_one := by
      intro a
      change smulFun a 1 = 1
      apply Subtype.ext
      simp [smulFun] }

theorem conjActionOfLeNormalizer_coe {X : Type*} [Group X] (A N : Subgroup X)
    (hAN : A ≤ Subgroup.normalizer (N : Set X)) (a : A) (n : N) :
    letI := conjActionOfLeNormalizer A N hAN
    ((a • n : N) : X) = (a : X) * (n : X) * (a : X)⁻¹ := rfl

end CoprimeAction
