module

public import Isaacs.FittingSubgroup
public import Mathlib.Data.Fintype.Lattice

/-!
# Subgroups of a `p`-group: `Z(P)`, `Ω₁(A)`, `E(P)` and the Thompson subgroup

Isaacs, *Finite Group Theory*, Chapter 7.  For a `p`-group `P`, `E(P)` is the set of elementary
abelian subgroups of `P` of the largest possible order, and the **Thompson subgroup** `J(P)` is
the subgroup they generate.  Lemma 7.2 says that `J(P)` is unchanged on passing to any subgroup
between `J(P)` and `P`:

> If `J(P) ⊆ Q ⊆ P`, where `P` is a `p`-group, then `J(P) = J(Q)`, and in particular `J(P)` is
> characteristic in `Q`.

`mathlib` has neither elementary abelian groups nor the Thompson subgroup.  (The Qiuzhen CFSG
development does define a `thompsonSubgroup`, but for the *abelian* subgroups of largest order —
Gorenstein's `J`, a different subgroup in general.)

Everything here is relative to an ambient group, in the style of `PiGroups.piPart`: `P` is a
subgroup of `G` and `PiGroups.thompsonSubgroup p P` is a subgroup of `G`.  Nothing in this file
needs `P` to be a `p`-group; `p` is a parameter of the definitions, and in the application it is
the prime for which `P` is a Sylow subgroup.

This file collects the subgroup constructions that Chapter 7 builds on, and the facts about them
that its three main theorems — 7.1 (`Isaacs/ThompsonNormalPComplement.lean`), 7.6
(`Isaacs/NormalJTheorem.lean`) and 7.8 (`Isaacs/BurnsidePQTheorem.lean`) — share:

* `PiGroups.centerOf P` is `Z(P)`, ambiently: `Z(P) = P ⊓ C_G(P)`.  `Z(P)` appears in the
  hypotheses of both 7.1 and 7.6, as `C_G(Z(P)) = P`;
* `PiGroups.IsElementaryAbelian`: commutative, of exponent dividing `p`;
* `PiGroups.omegaOne p A` is `Ω₁(A)`, the subgroup generated by the elements of `A` killed by `p`.
  For abelian `A` — the only case used — it is exactly the set of such elements
  (`PiGroups.omegaOne_eq_of_commute`) and so is elementary abelian
  (`PiGroups.isElementaryAbelian_omegaOne`); it is normal whenever `A` is
  (`PiGroups.omegaOne_normal`) and nontrivial whenever `A` is a nontrivial `p`-group
  (`PiGroups.omegaOne_ne_bot`).  Step 8 of 7.6 needs all four, for the elementary abelian module
  `V = Ω₁(Z(O_p(G)))` it feeds to the normal-`P` theorem 7.5;
* `PiGroups.maxElemAb p P` is Isaacs' `E(P)` and `PiGroups.thompsonSubgroup p P` is `J(P)`;
* `PiGroups.maxElemAb_eq_of_thompsonSubgroup_le` and
  `PiGroups.thompsonSubgroup_eq_of_thompsonSubgroup_le` are **Lemma 7.2**;
* `PiGroups.thompsonSubgroup_characteristic` says `J(Q)` is characteristic in `Q` — the
  automorphisms of `Q` permute `E(Q)` — and
  `PiGroups.thompsonSubgroup_characteristic_of_le` is the "in particular" of 7.2;
* `PiGroups.map_conj_of_characteristic_subgroupOf`,
  `PiGroups.normal_of_characteristic_subgroupOf` and
  `PiGroups.le_normalizer_of_characteristic_subgroupOf` transfer that conclusion upwards: a
  subgroup characteristic in a normal subgroup is normal, and one characteristic in any `N` has
  `N` inside its normalizer.  Applied to `J`, this is how each of the three theorems turns
  "characteristic in `Q`" into normality or a normalizer bound.
-/

@[expose] public section

namespace PiGroups

universe u

variable {G : Type u} [Group G] {p : ℕ}

/-!
## The centre of a subgroup, ambiently
-/

/-- `Z(P)` as a subgroup of the ambient group: `Z(P) = P ⊓ C_G(P)`. -/
def centerOf (P : Subgroup G) : Subgroup G := P ⊓ Subgroup.centralizer (P : Set G)

theorem centerOf_le (P : Subgroup G) : centerOf P ≤ P := inf_le_left

theorem centerOf_le_centralizer (P : Subgroup G) :
    centerOf P ≤ Subgroup.centralizer (P : Set G) := inf_le_right

theorem le_centerOf {P A : Subgroup G} (hAP : A ≤ P)
    (hA : A ≤ Subgroup.centralizer (P : Set G)) : A ≤ centerOf P := le_inf hAP hA

/-- A subgroup centralizes its own centre. -/
theorem le_centralizer_centerOf (P : Subgroup G) :
    P ≤ Subgroup.centralizer ((centerOf P : Subgroup G) : Set G) := fun x hx =>
  Subgroup.mem_centralizer_iff.mpr fun _z hz =>
    (Subgroup.mem_centralizer_iff.mp (centerOf_le_centralizer P hz) x hx).symm

/-- `Z(P)` lies in `Z(Q)` for any `Q` between `Z(P)` and `P`. -/
theorem centerOf_le_centerOf_of_le {P Q : Subgroup G} (hZQ : centerOf P ≤ Q) (hQP : Q ≤ P) :
    centerOf P ≤ centerOf Q :=
  le_centerOf hZQ
    ((centerOf_le_centralizer P).trans (Subgroup.centralizer_le (SetLike.coe_subset_coe.mpr hQP)))

/-!
## Elementary abelian subgroups
-/

/-- An elementary abelian `p`-subgroup: commutative, with every element of order dividing `p`.
Stated elementwise, so that it transfers along homomorphisms without bookkeeping. -/
def IsElementaryAbelian (p : ℕ) (A : Subgroup G) : Prop :=
  (∀ x ∈ A, ∀ y ∈ A, x * y = y * x) ∧ ∀ x ∈ A, x ^ p = 1

namespace IsElementaryAbelian

theorem bot : IsElementaryAbelian p (⊥ : Subgroup G) := by
  constructor
  · intro x hx y hy
    rw [Subgroup.mem_bot.mp hx, Subgroup.mem_bot.mp hy]
  · intro x hx
    rw [Subgroup.mem_bot.mp hx, one_pow]

theorem of_le {A B : Subgroup G} (hB : IsElementaryAbelian p B) (hAB : A ≤ B) :
    IsElementaryAbelian p A :=
  ⟨fun x hx y hy => hB.1 x (hAB hx) y (hAB hy), fun x hx => hB.2 x (hAB hx)⟩

/-- Homomorphic images of elementary abelian subgroups are elementary abelian. -/
theorem map {H : Type*} [Group H] {A : Subgroup G} (hA : IsElementaryAbelian p A) (f : G →* H) :
    IsElementaryAbelian p (A.map f) := by
  constructor
  · rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
    rw [← map_mul, ← map_mul, hA.1 x hx y hy]
  · rintro _ ⟨x, hx, rfl⟩
    rw [← map_pow, hA.2 x hx, map_one]

/-- Preimages under injective homomorphisms are elementary abelian. -/
theorem comap_of_injective {H : Type*} [Group H] {A : Subgroup G} (hA : IsElementaryAbelian p A)
    {f : H →* G} (hf : Function.Injective f) : IsElementaryAbelian p (A.comap f) := by
  constructor
  · intro x hx y hy
    refine hf ?_
    rw [map_mul, map_mul]
    exact hA.1 (f x) hx (f y) hy
  · intro x hx
    refine hf ?_
    rw [map_pow, map_one]
    exact hA.2 (f x) hx

/-- An elementary abelian subgroup is a `p`-group. -/
theorem isPGroup {A : Subgroup G} (hA : IsElementaryAbelian p A) : IsPGroup p A :=
  fun x => ⟨1, by
    rw [pow_one]
    exact Subtype.ext (by simpa using hA.2 (x : G) x.2)⟩

end IsElementaryAbelian

/-!
## The elementary abelian subgroup `Ω₁(A)`

For an *abelian* `A` the elements killed by `p` already form a subgroup; defining `Ω₁` as the
subgroup they generate makes the definition total and its invariance under conjugation immediate.
-/

variable (p) in
/-- `Ω₁(A)`: the subgroup generated by the elements of `A` killed by `p`.  For abelian `A` — the
only case used — this is exactly the set of such elements, by `omegaOne_eq_of_commute`. -/
def omegaOne (A : Subgroup G) : Subgroup G :=
  Subgroup.closure {x : G | x ∈ A ∧ x ^ p = 1}

theorem omegaOne_le (A : Subgroup G) : omegaOne p A ≤ A :=
  (Subgroup.closure_le _).mpr fun _ hx => hx.1

theorem mem_omegaOne {A : Subgroup G} {x : G} (hxA : x ∈ A) (hx : x ^ p = 1) :
    x ∈ omegaOne p A :=
  Subgroup.subset_closure ⟨hxA, hx⟩

/-- For an abelian `A` the elements killed by `p` already form a subgroup, so `Ω₁(A)` is exactly
that set. -/
theorem omegaOne_eq_of_commute {A : Subgroup G} (hA : ∀ x ∈ A, ∀ y ∈ A, x * y = y * x) :
    (omegaOne p A : Set G) = {x : G | x ∈ A ∧ x ^ p = 1} := by
  refine le_antisymm ?_ fun x hx => mem_omegaOne hx.1 hx.2
  exact (Subgroup.closure_le
    ({ carrier := {x : G | x ∈ A ∧ x ^ p = 1}
       one_mem' := ⟨one_mem A, one_pow p⟩
       mul_mem' := fun {a b} ha hb => ⟨mul_mem ha.1 hb.1, by
         rw [Commute.mul_pow (hA _ ha.1 _ hb.1), ha.2, hb.2, one_mul]⟩
       inv_mem' := fun {a} ha => ⟨inv_mem ha.1, by rw [inv_pow, ha.2, inv_one]⟩ } :
      Subgroup G)).mpr fun _ hx => hx

/-- `Ω₁` of an abelian subgroup is elementary abelian. -/
theorem isElementaryAbelian_omegaOne {A : Subgroup G}
    (hA : ∀ x ∈ A, ∀ y ∈ A, x * y = y * x) : IsElementaryAbelian p (omegaOne p A) := by
  refine ⟨fun x hx y hy => hA x (omegaOne_le A hx) y (omegaOne_le A hy), fun x hx => ?_⟩
  have hmem : x ∈ (omegaOne p A : Set G) := hx
  rw [omegaOne_eq_of_commute hA] at hmem
  exact hmem.2

/-- Conjugation preserves `Ω₁`, so `Ω₁(A)` is normal whenever `A` is. -/
instance omegaOne_normal {A : Subgroup G} [hA : A.Normal] : (omegaOne p A).Normal := by
  refine ⟨fun n hn g => ?_⟩
  have hmap : (omegaOne p A).map (MulAut.conj g).toMonoidHom ≤ omegaOne p A := by
    rw [omegaOne, Subgroup.map_le_iff_le_comap]
    refine (Subgroup.closure_le _).mpr ?_
    rintro x ⟨hxA, hx⟩
    refine Subgroup.mem_comap.mpr (mem_omegaOne (hA.conj_mem x hxA g) ?_)
    have hc : (g * x * g⁻¹) ^ p = g * x ^ p * g⁻¹ := by simp
    change (g * x * g⁻¹) ^ p = 1
    rw [hc, hx, mul_one, mul_inv_cancel]
  exact hmap ⟨n, hn, rfl⟩

/-- `Ω₁` of a nontrivial finite `p`-group is nontrivial, by Cauchy. -/
theorem omegaOne_ne_bot [Finite G] [Fact p.Prime] {A : Subgroup G} (hAp : IsPGroup p ↥A)
    (hA : A ≠ ⊥) : omegaOne p A ≠ ⊥ := by
  obtain ⟨k, hk⟩ := hAp.exists_card_eq
  have hk0 : k ≠ 0 := fun h => hA (Subgroup.eq_bot_of_card_eq _ (by rw [hk, h, pow_zero]))
  obtain ⟨x, hx⟩ := exists_prime_orderOf_dvd_card' (G := ↥A) p
    (by rw [hk]; exact dvd_pow_self p hk0)
  intro hbot
  have hpow : ((x : G)) ^ p = 1 := by
    have h1 := pow_orderOf_eq_one x
    rw [hx] at h1
    exact congrArg Subtype.val h1
  have hmem : ((x : G)) ∈ omegaOne p A := mem_omegaOne x.2 hpow
  rw [hbot, Subgroup.mem_bot] at hmem
  have : orderOf x = 1 := by rw [← Subgroup.orderOf_coe, hmem, orderOf_one]
  rw [hx] at this
  exact (Fact.out : p.Prime).one_lt.ne' this

/-!
## `E(P)` and `J(P)`
-/

/-- Isaacs' `E(P)`: the elementary abelian subgroups of `P` of the largest possible order. -/
def maxElemAb (p : ℕ) (P : Subgroup G) : Set (Subgroup G) :=
  {A : Subgroup G | A ≤ P ∧ IsElementaryAbelian p A ∧
    ∀ B : Subgroup G, B ≤ P → IsElementaryAbelian p B → Nat.card B ≤ Nat.card A}

variable (p) in
/-- The **Thompson subgroup** `J(P)`: the subgroup generated by the elementary abelian subgroups
of `P` of largest order. -/
def thompsonSubgroup (P : Subgroup G) : Subgroup G :=
  ⨆ (A : Subgroup G) (_ : A ∈ maxElemAb p P), A

theorem le_of_mem_maxElemAb {P A : Subgroup G} (hA : A ∈ maxElemAb p P) : A ≤ P := hA.1

theorem isElementaryAbelian_of_mem_maxElemAb {P A : Subgroup G} (hA : A ∈ maxElemAb p P) :
    IsElementaryAbelian p A := hA.2.1

theorem card_le_of_mem_maxElemAb {P A B : Subgroup G} (hA : A ∈ maxElemAb p P) (hBP : B ≤ P)
    (hB : IsElementaryAbelian p B) : Nat.card B ≤ Nat.card A := hA.2.2 B hBP hB

theorem le_thompsonSubgroup {P A : Subgroup G} (hA : A ∈ maxElemAb p P) :
    A ≤ thompsonSubgroup p P :=
  le_iSup₂ (f := fun (A : Subgroup G) (_ : A ∈ maxElemAb p P) => A) A hA

theorem thompsonSubgroup_le (p : ℕ) (P : Subgroup G) : thompsonSubgroup p P ≤ P :=
  iSup₂_le fun _ hA => hA.1

/-- In a finite group there is an elementary abelian subgroup of largest order: `E(P) ≠ ∅`. -/
theorem maxElemAb_nonempty [Finite G] (p : ℕ) (P : Subgroup G) : (maxElemAb p P).Nonempty := by
  classical
  have : Finite (Subgroup G) :=
    Finite.of_injective (fun U : Subgroup G => (U : Set G)) SetLike.coe_injective
  set ℰ : Set (Subgroup G) := {A : Subgroup G | A ≤ P ∧ IsElementaryAbelian p A} with hℰ
  have hmem : ∀ A : Subgroup G, A ∈ ℰ ↔ (A ≤ P ∧ IsElementaryAbelian p A) := by
    intro A
    rw [hℰ]
    exact Iff.rfl
  have : Nonempty ↥ℰ := ⟨⟨⊥, (hmem ⊥).mpr ⟨bot_le, IsElementaryAbelian.bot⟩⟩⟩
  obtain ⟨A₀, hA₀⟩ := Finite.exists_max fun A : ↥ℰ => Nat.card (A : Subgroup G)
  obtain ⟨hA₀P, hA₀ea⟩ := (hmem _).mp A₀.2
  exact ⟨(A₀ : Subgroup G), hA₀P, hA₀ea, fun B hBP hB => hA₀ ⟨B, (hmem B).mpr ⟨hBP, hB⟩⟩⟩

/-- A cyclic group of prime order is elementary abelian. -/
theorem isElementaryAbelian_zpowers {y : G} (hy : orderOf y = p) :
    IsElementaryAbelian p (Subgroup.zpowers y) := by
  have hyp : y ^ p = 1 := by
    rw [← hy]
    exact pow_orderOf_eq_one y
  constructor
  · rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    exact ((Commute.refl y).zpow_zpow m n).eq
  · rintro _ ⟨n, rfl⟩
    rw [← zpow_natCast (y ^ n) p, ← zpow_mul, mul_comm, zpow_mul, zpow_natCast, hyp, one_zpow]

/-- The Thompson subgroup of a nontrivial `p`-group is nontrivial: an element of order `p`
generates an elementary abelian subgroup, so the members of `E(P)` have order at least `p`. -/
theorem thompsonSubgroup_ne_bot [Finite G] (hp : p.Prime) {P : Subgroup G} (hPp : IsPGroup p P)
    (hPbot : P ≠ ⊥) : thompsonSubgroup p P ≠ ⊥ := by
  have : Fact p.Prime := ⟨hp⟩
  have hnt : Nontrivial ↥P := (Subgroup.nontrivial_iff_ne_bot P).mpr hPbot
  obtain ⟨n, hn⟩ := hPp.exists_card_eq
  have hpdvd : p ∣ Nat.card ↥P := by
    rw [hn]
    refine dvd_pow_self p fun h0 => hPbot ?_
    rw [h0, pow_zero] at hn
    exact Subgroup.card_eq_one.mp hn
  obtain ⟨y, hy⟩ := exists_prime_orderOf_dvd_card' (G := ↥P) p hpdvd
  have hyP : Subgroup.zpowers (y : G) ≤ P := by
    rw [Subgroup.zpowers_le]
    exact y.2
  have hycard : Nat.card ↥(Subgroup.zpowers (y : G)) = p := by
    rw [Nat.card_zpowers, Subgroup.orderOf_coe, hy]
  obtain ⟨A, hA⟩ := maxElemAb_nonempty p P
  have hAcard : p ≤ Nat.card ↥A :=
    hycard ▸ hA.2.2 _ hyP (isElementaryAbelian_zpowers (by rw [Subgroup.orderOf_coe, hy]))
  intro hbot
  have hA1 : Nat.card ↥A = 1 := by
    rw [Subgroup.card_eq_one]
    exact le_bot_iff.mp ((le_thompsonSubgroup hA).trans hbot.le)
  have := hp.one_lt
  omega

/-!
## Isaacs' Lemma 7.2
-/

/-- **Isaacs, Lemma 7.2.**  If `J(P) ≤ Q ≤ P` then `P` and `Q` have the same elementary abelian
subgroups of largest order.

Every member of `E(P)` lies in `J(P) ≤ Q`, and is of largest order among the elementary abelian
subgroups of `Q` because `Q ≤ P`; conversely a member of `E(Q)` is at least as large as those, so
it has their order and is a member of `E(P)`. -/
theorem maxElemAb_eq_of_thompsonSubgroup_le [Finite G] {P Q : Subgroup G}
    (hJQ : thompsonSubgroup p P ≤ Q) (hQP : Q ≤ P) : maxElemAb p Q = maxElemAb p P := by
  have hPQ : maxElemAb p P ⊆ maxElemAb p Q := by
    intro A hA
    exact ⟨(le_thompsonSubgroup hA).trans hJQ, hA.2.1,
      fun B hBQ hB => hA.2.2 B (hBQ.trans hQP) hB⟩
  refine Set.eq_of_subset_of_subset (fun B hB => ?_) hPQ
  obtain ⟨A, hA⟩ := maxElemAb_nonempty p P
  refine ⟨hB.1.trans hQP, hB.2.1, fun C hCP hC => ?_⟩
  exact (hA.2.2 C hCP hC).trans (hB.2.2 A (hPQ hA).1 hA.2.1)

/-- **Isaacs, Lemma 7.2.**  If `J(P) ≤ Q ≤ P` then `J(Q) = J(P)`. -/
theorem thompsonSubgroup_eq_of_thompsonSubgroup_le [Finite G] {P Q : Subgroup G}
    (hJQ : thompsonSubgroup p P ≤ Q) (hQP : Q ≤ P) :
    thompsonSubgroup p Q = thompsonSubgroup p P := by
  rw [thompsonSubgroup, thompsonSubgroup, maxElemAb_eq_of_thompsonSubgroup_le hJQ hQP]

/-!
## `J(Q)` is characteristic in `Q`
-/

/-- The Thompson subgroup, seen inside `Q`, is the join of the members of `E(Q)` seen inside
`Q`. -/
theorem subgroupOf_thompsonSubgroup (p : ℕ) (Q : Subgroup G) :
    (thompsonSubgroup p Q).subgroupOf Q
      = ⨆ (A : Subgroup G) (_ : A ∈ maxElemAb p Q), A.subgroupOf Q := by
  refine Subgroup.map_injective Q.subtype_injective ?_
  rw [Subgroup.subgroupOf_map_subtype, inf_eq_left.mpr (thompsonSubgroup_le p Q), thompsonSubgroup]
  simp only [Subgroup.map_iSup, Subgroup.subgroupOf_map_subtype]
  exact iSup_congr fun A => iSup_congr fun hA => (inf_eq_left.mpr hA.1).symm

/-- Automorphisms of `Q` permute `E(Q)`, so **`J(Q)` is characteristic in `Q`**. -/
instance thompsonSubgroup_characteristic [Finite G] (p : ℕ) (Q : Subgroup G) :
    ((thompsonSubgroup p Q).subgroupOf Q).Characteristic := by
  rw [Subgroup.characteristic_iff_map_le]
  intro φ
  rw [Subgroup.map_le_iff_le_comap, subgroupOf_thompsonSubgroup]
  refine iSup₂_le fun A hA => ?_
  rw [← Subgroup.map_le_iff_le_comap]
  -- the image of `A` under `φ`, back in the ambient group, is again a member of `E(Q)`
  have hAsub : IsElementaryAbelian p (A.subgroupOf Q) :=
    hA.2.1.comap_of_injective Q.subtype_injective
  have hcard : Nat.card ↥(((A.subgroupOf Q).map φ.toMonoidHom).map Q.subtype) = Nat.card A := by
    rw [Subgroup.card_map_of_injective Q.subtype_injective,
      Subgroup.card_map_of_injective (f := φ.toMonoidHom) φ.injective]
    exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe hA.1).toEquiv
  have hBmem : ((A.subgroupOf Q).map φ.toMonoidHom).map Q.subtype ∈ maxElemAb p Q :=
    ⟨Subgroup.map_subtype_le _, (hAsub.map φ.toMonoidHom).map Q.subtype,
      fun B hBQ hB => (hA.2.2 B hBQ hB).trans hcard.ge⟩
  have hBeq : (A.subgroupOf Q).map φ.toMonoidHom
      = (((A.subgroupOf Q).map φ.toMonoidHom).map Q.subtype).subgroupOf Q :=
    (Subgroup.comap_map_eq_self_of_injective Q.subtype_injective _).symm
  rw [hBeq]
  exact le_iSup₂_of_le _ hBmem le_rfl

/-- **Isaacs, Lemma 7.2**, second half: if `J(P) ≤ Q ≤ P` then `J(P)` is characteristic in `Q`. -/
theorem thompsonSubgroup_characteristic_of_le [Finite G] {P Q : Subgroup G}
    (hJQ : thompsonSubgroup p P ≤ Q) (hQP : Q ≤ P) :
    ((thompsonSubgroup p P).subgroupOf Q).Characteristic := by
  rw [← thompsonSubgroup_eq_of_thompsonSubgroup_le hJQ hQP]
  infer_instance

/-!
## Characteristic subgroups of normal subgroups
-/

/-- Conjugation stabilizing `N` stabilizes any subgroup characteristic in `N`. -/
theorem map_conj_of_characteristic_subgroupOf {N K : Subgroup G} {g : G} (hKN : K ≤ N)
    (hchar : (K.subgroupOf N).Characteristic)
    (hg : N.map (MulAut.conj g).toMonoidHom = N) :
    K.map (MulAut.conj g).toMonoidHom = K := by
  let e : ↥N ≃* ↥N := ((MulAut.conj g).subgroupMap N).trans (MulEquiv.subgroupCongr hg)
  have hc : (K.subgroupOf N).map e.toMonoidHom = K.subgroupOf N :=
    Subgroup.characteristic_iff_map_eq.mp hchar e
  have hcomp : N.subtype.comp e.toMonoidHom = ((MulAut.conj g).toMonoidHom).comp N.subtype :=
    MonoidHom.ext fun _ => rfl
  calc K.map (MulAut.conj g).toMonoidHom
      = ((K.subgroupOf N).map N.subtype).map (MulAut.conj g).toMonoidHom := by
        rw [Subgroup.subgroupOf_map_subtype, inf_eq_left.mpr hKN]
    _ = (K.subgroupOf N).map (((MulAut.conj g).toMonoidHom).comp N.subtype) := by
        rw [Subgroup.map_map]
    _ = (K.subgroupOf N).map (N.subtype.comp e.toMonoidHom) := by rw [hcomp]
    _ = ((K.subgroupOf N).map e.toMonoidHom).map N.subtype := by rw [← Subgroup.map_map]
    _ = K := by rw [hc, Subgroup.subgroupOf_map_subtype, inf_eq_left.mpr hKN]

/-- A subgroup characteristic in a normal subgroup is normal. -/
theorem normal_of_characteristic_subgroupOf {N K : Subgroup G} [hN : N.Normal] (hKN : K ≤ N)
    (hchar : (K.subgroupOf N).Characteristic) : K.Normal := by
  rw [← Subgroup.normalizer_eq_top_iff]
  refine top_le_iff.mp fun g _ => map_conj_eq_self_iff.mp ?_
  exact map_conj_of_characteristic_subgroupOf hKN hchar
    (map_conj_eq_self_iff.mpr
      (by rw [Subgroup.normalizer_eq_top N]; exact Subgroup.mem_top g))

/-- A subgroup normalized by everything that normalizes `N` and characteristic in `N`. -/
theorem le_normalizer_of_characteristic_subgroupOf {N K M : Subgroup G} (hKN : K ≤ N)
    (hchar : (K.subgroupOf N).Characteristic) (hM : M ≤ Subgroup.normalizer (N : Set G)) :
    M ≤ Subgroup.normalizer (K : Set G) := fun _g hg =>
  map_conj_eq_self_iff.mp
    (map_conj_of_characteristic_subgroupOf hKN hchar (map_conj_eq_self_iff.mpr (hM hg)))

end PiGroups
