module

public import PreCFSG.CoprimeQuotients

/-!
# The commutator of a coprime action

Isaacs, *Finite Group Theory*, Lemmas 4.28 and 4.29:

* `CoprimeAction.fixedPoints_sup_commutatorAction_eq_top` (4.28): if `(|G|,|A|) = 1` and one of
  `A`, `G` is solvable, then `G = C_G(A)⁅G, A⁆`;
* `CoprimeAction.commutatorAction₂_eq` (4.29): if `(|G|,|A|) = 1` then `⁅G, A, A⁆ = ⁅G, A⁆`, with
  no solvability hypothesis.

`⁅H, A⁆` is `CoprimeAction.commutatorSubgroup`, the subgroup generated by the elements
`h⁻¹ * (a • h)`; the naming and the convention agree with the Qiuzhen CFSG development's
`commutatorSubgroup` / `commutatorAction` / `commutatorAction₂`, whose
`FeitThompson/GroupAction/CoprimeHall.lean` proves both statements under the stronger hypothesis
that `G` is solvable.  `mathlib` has no commutator for an action at all.

4.28 is 3.28 applied to `N = ⁅G, A⁆`, on whose quotient `A` acts trivially by construction.  4.29
follows for solvable `A` from 4.28, and in general by applying that case to the cyclic — hence
solvable — subgroup `⟨a⟩` of `A`, which is Isaacs' argument.
-/

@[expose] public section

namespace CoprimeAction

open scoped Pointwise

universe u

variable {G A : Type u} [Group G] [Group A] [MulDistribMulAction A G]

/-!
## The commutator subgroup of an action
-/

/-- The commutator `⁅H, A⁆` of a subgroup `H ≤ G` with the action of `A`: the subgroup generated
by the elements `h⁻¹ * (a • h)` for `h ∈ H` and `a ∈ A`. -/
def commutatorSubgroup (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G]
    (H : Subgroup G := ⊤) : Subgroup G :=
  Subgroup.closure {x : G | ∃ a : A, ∃ h : G, h ∈ H ∧ x = h⁻¹ * (a • h)}

/-- The commutator `⁅G, A⁆` of the whole group with the action. -/
abbrev commutatorAction (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G] :
    Subgroup G := commutatorSubgroup A G ⊤

/-- The iterated commutator `⁅G, A, A⁆`. -/
abbrev commutatorAction₂ (A G : Type u) [Group A] [Group G] [MulDistribMulAction A G] :
    Subgroup G := commutatorSubgroup A G (commutatorAction A G)

theorem mem_commutatorSubgroup_gen {H : Subgroup G} (a : A) {h : G} (hh : h ∈ H) :
    h⁻¹ * (a • h) ∈ commutatorSubgroup A G H :=
  Subgroup.subset_closure ⟨a, h, hh, rfl⟩

theorem commutatorSubgroup_le {H K : Subgroup G}
    (hgen : ∀ (a : A), ∀ h ∈ H, h⁻¹ * (a • h) ∈ K) : commutatorSubgroup A G H ≤ K := by
  refine Subgroup.closure_le _ |>.mpr ?_
  rintro x ⟨a, h, hh, rfl⟩
  exact hgen a h hh

/-- `⁅G, A⁆` is `A`-invariant: `b • ⁅g, a⁆ = ⁅b • g, bab⁻¹⁆`. -/
theorem smul_mem_commutatorAction (b : A) {n : G} (hn : n ∈ commutatorAction A G) :
    b • n ∈ commutatorAction A G := by
  induction hn using Subgroup.closure_induction with
  | mem y hy =>
    obtain ⟨a, h, -, rfl⟩ := hy
    have key : b • (h⁻¹ * (a • h)) = (b • h)⁻¹ * ((b * a * b⁻¹) • (b • h)) := by
      rw [smul_mul', smul_inv', ← mul_smul, ← mul_smul]
      congr 2
      group
    rw [key]
    exact mem_commutatorSubgroup_gen _ (Subgroup.mem_top _)
  | one => simp
  | mul y z _ _ hy hz =>
    rw [smul_mul']
    exact mul_mem hy hz
  | inv y _ hy =>
    rw [smul_inv']
    exact inv_mem hy

/-- `⁅G, A⁆` is normal in `G`: `⁅gx, a⁆ = ⁅g, a⁆ˣ ⁅x, a⁆`. -/
instance commutatorAction_normal : (commutatorAction A G).Normal := by
  constructor
  intro n hn x
  induction hn using Subgroup.closure_induction with
  | mem y hy =>
    obtain ⟨a, h, -, rfl⟩ := hy
    have hexp : a • (h * x⁻¹) = (a • h) * (a • x⁻¹) := smul_mul' a h x⁻¹
    have key : x * (h⁻¹ * (a • h)) * x⁻¹
        = ((h * x⁻¹)⁻¹ * (a • (h * x⁻¹))) * ((x⁻¹)⁻¹ * (a • x⁻¹))⁻¹ := by
      rw [hexp]
      group
    rw [key]
    exact mul_mem (mem_commutatorSubgroup_gen a (Subgroup.mem_top _))
      (inv_mem (mem_commutatorSubgroup_gen a (Subgroup.mem_top _)))
  | one => simp
  | mul y z _ _ hy hz =>
    have hrw : x * (y * z) * x⁻¹ = (x * y * x⁻¹) * (x * z * x⁻¹) := by group
    rw [hrw]
    exact mul_mem hy hz
  | inv y _ hy =>
    have hrw : x * y⁻¹ * x⁻¹ = (x * y * x⁻¹)⁻¹ := by group
    rw [hrw]
    exact inv_mem hy

theorem smul_mem_commutatorAction' : ∀ (a : A), ∀ n ∈ commutatorAction A G,
    a • n ∈ commutatorAction A G := fun a _ hn ↦ smul_mem_commutatorAction a hn

/-- By construction, `A` acts trivially on `G ⧸ ⁅G, A⁆`. -/
theorem smul_mk_commutatorAction (a : A) (x : G ⧸ commutatorAction A G) :
    letI := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
    a • x = x := by
  let := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
  induction x using QuotientGroup.induction_on with
  | _ y =>
    rw [quotientAction_mk]
    refine QuotientGroup.eq.mpr ?_
    have hmem : y⁻¹ * (a • y) ∈ commutatorAction A G :=
      mem_commutatorSubgroup_gen a (Subgroup.mem_top _)
    simpa using inv_mem hmem

/-- `⁅G, A, A⁆ ≤ ⁅G, A⁆`, since `⁅G, A⁆` is `A`-invariant. -/
theorem commutatorAction₂_le : commutatorAction₂ A G ≤ commutatorAction A G :=
  commutatorSubgroup_le fun a _ hh ↦ mul_mem (inv_mem hh) (smul_mem_commutatorAction a hh)

variable [Finite G] [Finite A]

/-!
## Isaacs 4.28
-/

/-- **Isaacs, Lemma 4.28.**  For a coprime action with `A` or `G` solvable, `G = C_G(A)⁅G, A⁆`. -/
theorem fixedPoints_sup_commutatorAction_eq_top (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G))
    (hsolv : Group.IsSolvable A ∨ Group.IsSolvable G) :
    FixedPoints.subgroup A G ⊔ commutatorAction A G = ⊤ := by
  let := quotientAction (smul_mem_commutatorAction' (A := A) (G := G))
  have hcop' : Nat.Coprime (Nat.card A) (Nat.card (commutatorAction A G)) :=
    Nat.Coprime.coprime_dvd_right (Subgroup.card_subgroup_dvd_card _) hcop
  have hsolv' : Group.IsSolvable A ∨ Group.IsSolvable (commutatorAction A G) :=
    hsolv.imp id fun hG ↦ by have := hG; exact inferInstance
  exact fixedPoints_sup_eq_top hSZ (smul_mem_commutatorAction' (A := A) (G := G)) hcop' hsolv'
    (quotientAction_mk _) smul_mk_commutatorAction

/-!
## Isaacs 4.29
-/

/-- Isaacs 4.29 when the operator group is solvable: if `g = cx` with `c` fixed and `x ∈ ⁅G, A⁆`
then `⁅g, a⁆ = ⁅x, a⁆`. -/
theorem commutatorAction₂_eq_of_isSolvable (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G)) (hsolvA : Group.IsSolvable A) :
    commutatorAction₂ A G = commutatorAction A G := by
  refine le_antisymm commutatorAction₂_le (commutatorSubgroup_le fun a g _ ↦ ?_)
  have hg : g ∈ (FixedPoints.subgroup A G : Set G) * (commutatorAction A G : Set G) := by
    rw [← Subgroup.mul_normal]
    rw [fixedPoints_sup_commutatorAction_eq_top hSZ hcop (Or.inl hsolvA)]
    trivial
  obtain ⟨c, hc, x, hx, rfl⟩ := hg
  have hca : a • c = c := hc a
  have key : (c * x)⁻¹ * (a • (c * x)) = x⁻¹ * (a • x) := by
    rw [smul_mul', hca]
    group
  rw [key]
  exact mem_commutatorSubgroup_gen a hx

/-- **Isaacs, Lemma 4.29.**  For any coprime action, `⁅G, A, A⁆ = ⁅G, A⁆`; no solvability is
needed, because it suffices to treat one automorphism at a time and `⟨a⟩` is cyclic. -/
theorem commutatorAction₂_eq (hSZ : SchurZassenhausConjugacy.{u})
    (hcop : Nat.Coprime (Nat.card A) (Nat.card G)) :
    commutatorAction₂ A G = commutatorAction A G := by
  refine le_antisymm commutatorAction₂_le (commutatorSubgroup_le fun a g _ ↦ ?_)
  -- restrict the action to the cyclic subgroup generated by `a`
  let : MulDistribMulAction (Subgroup.zpowers a) G :=
    MulDistribMulAction.compHom G (Subgroup.zpowers a).subtype
  have hcopK : Nat.Coprime (Nat.card (Subgroup.zpowers a)) (Nat.card G) :=
    Nat.Coprime.coprime_dvd_left (Subgroup.card_subgroup_dvd_card _) hcop
  have hK := commutatorAction₂_eq_of_isSolvable (A := Subgroup.zpowers a) (G := G) hSZ hcopK
    (Group.isSolvable_of_comm fun x y ↦ mul_comm' x y)
  -- the commutators for `⟨a⟩` are commutators for `A`
  have htrans : ∀ H H' : Subgroup G, H ≤ H' →
      commutatorSubgroup (Subgroup.zpowers a) G H ≤ commutatorSubgroup A G H' := by
    intro H H' hHH'
    exact commutatorSubgroup_le fun b h hh ↦ mem_commutatorSubgroup_gen (b : A) (hHH' hh)
  have h1 : g⁻¹ * (a • g) ∈ commutatorAction (Subgroup.zpowers a) G :=
    mem_commutatorSubgroup_gen (⟨a, Subgroup.mem_zpowers a⟩ : Subgroup.zpowers a)
      (Subgroup.mem_top _)
  rw [← hK] at h1
  exact htrans _ _ (htrans _ _ le_rfl) h1

end CoprimeAction
